
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: LineUpChecker_development

production:
  <<: *default
  database: LineUpChecker_production
  username: LineUpChecker
  password: <%= ENV['LINEUPCHECKER_DATABASE_PASSWORD'] %>
